### PR TITLE
Adding Rinkedry

### PR DESCRIPTION
**Pull request by shan8851**
I recently created a Rinkeby Faucet as a learning project. After receiving some solid feedback I figured it might be useful to others and this seems like a good spot to spread the word.

### CODE REVIEW

**Comment by arddluma** [comment]
Hey,
Could you please add full url, you have added only rinkedry without tld.

**Comment by shan8851** [comment]
Hey, sorry man, copy pasta is hard sometimes... Edited now

**Comment by arddluma** [comment]
This is so cool man @shan8851 ! Just a suggestion, it would be great if you add WalletConnect support so users can use dApp from mobile 💯
Will merge this, also just added you in Twitter! See ya there !
Keep BUIDLing 🚀

**Comment by shan8851** [comment]
Thanks for the kind words man! Still early in my learning days, but yeah, I think adding wallet connect for mobile support is a great shout. I will get to work on this!

**Pull request merged**
